services:
  postgres:
    image: postgres:17
    restart: on-failure
    environment:
      - POSTGRES_DB=dictionary
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    #    healthcheck:
    #      test: [ "CMD-SHELL", "pg_isready" ]
    #      interval: 1s
    #      timeout: 5s
    #      retries: 10
    networks:
      - dictionary-network
    ports:
      - "5433:5432"
    volumes:
      - dictionary-db:/var/lib/postgresql/data


networks:
  dictionary-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  dictionary-db:
    name: dictionary-db