version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dictionary-db
    restart: always
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
