spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dictionary
    username: postgres
    password: 12345

server:
  servlet:
    context-path: /api

mybatis:
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:config/mybatis.xml

springdoc:
  api-docs:
    path: /dictionary/api-docs
  swagger-ui:
    path: /dictionary/swagger-ui.html