spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${jdbc.url:jdbc:postgresql://localhost:5432/dictionary}
    username: ${jdbc.username:postgres}
    password: ${jdbc.password:313}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /dictionary/api-docs
  swagger-ui:
    path: /dictionary/swagger-ui.html