spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${jdbc.url:jdbc:postgresql://localhost/dictionary}
    username: ${jdbc.username:postgres}
    password: ${jdbc.password:postgres}

server:
  servlet:
    context-path: /api

mybatis:
  mapperLocations: classpath:sql/*.xml
  config-location: classpath:config/mybatis.xml

springdoc:
  api-docs:
    path: /dictionary/api-docs
  swagger-ui:
    path: /dictionary/swagger-ui.html