spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dictionary_service_db
    username: postgres
    password: root

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

mybatis:
  mapperLocations:
    - classpath:/sql/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /api/dictionary/api-docs
  swagger-ui:
    path: /api/dictionary/swagger-ui.html



