spring:
  application:
    name: DIPS-Dictionary-Service
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${jdbc.url:jdbc:postgresql://localhost/dictionary}
    username: ${jdbc.username:postgres}
    password: ${jdbc.password:postgres}
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false

mybatis:
  mapperLocations:
    - classpath:/mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /api/dictionary/api-docs
  swagger-ui:
    path: /api/dictionary/swagger-ui.html