spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  redis:
    host: localhost
    port: ${REDIS_PORT}

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: az.cybernet.internship.dictionary
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /api/dictionary/api-docs
  swagger-ui:
    path: /api/dictionary/swagger-ui.html
