spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/testdb
    username: testuser
    password: 404911
    #url: ${jdbc.url:jdbc:postgresql://localhost/dictionary}
    #username: ${jdbc.username:postgres}
    #password: ${jdbc.password:postgres}
    #url: jdbc:postgresql://localhost:5432/postgres
    #username: postgres
    #password: mypassword
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


mybatis:
  mapperLocations:
    - classpath:/mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /api/dictionary/api-docs
  swagger-ui:
    path: /api/dictionary/swagger-ui.html
